[versions]
agp = "8.8.1"
kotlin = "1.9.24"
playServicesWearable = "18.0.0"
wear = "1.3.0"
appcompat = "1.6.1"
corektx = "1.13.1"

[libraries]
play-services-wearable = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "playServicesWearable" }
wear = { group = "androidx.wear", name = "wear", version.ref = "wear" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "corektx" }
healthservices = { group = "androidx.health", name = "health-services-client", version = "1.1.0-alpha05" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

